- hosts: localhost                                  
  tasks:   
    - azure_rm_resourcegroup:                       
        location: "{{location}}"                    
        name: "{{resourcegroup}}"  
      name: Create Azure resource group
           
    - azure_rm_sqlserver:                           
        admin_password: "{{password}}"              
        admin_username: "{{admin}}"                 
        name: "{{sqlserver}}"                       
        resource_group: "{{resourcegroup}}"          
        version: "12.0"    
        administrators:
          azure_ad_only_authentication = true
          minimal_tls_version = "1.2"
          public_network_access = "disabled"
      name: Create Azure SQL Server Logical host
  vars:    
    admin: gissqladmin
    location: eastasia
    password: "Abcdefg@1234567"
    resourcegroup: hackathon-mssql-demo-rg
    sqlserver: ansiblesqlhost
           
