- hosts: localhost                                  
  tasks:   
    - azure_rm_resourcegroup:                       
        location: "{{location}}"                    
        name: "{{resourcegroup}}"                   
        name: "Create Azure resource group"               
           
    - azure_rm_sqlserver:                           
        admin_password: "{{password}}"              
        admin_username: "{{admin}}"                 
        name: "{{sqlserver}}"                       
        resource_group: "{{resourcegroup}}"          
        version: "12.0"                             
        name: "Create Azure SQL Server Logical host"
  vars:    
    admin: gissqladmin
    location: eastasia
    password: "Abcdefg@1234567"
    resourcegroup: hackathon-mssql-demo-rg
    sqlserver: ansiblesqlhost
           
