- name: Install httpd package
  hosts: servera
  tasks: 
    - name: Ensure httpd package is present
      ansible.builtin.dnf:
        name: httpd
        state: present
    - name: Ensure httpd service is started
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
    - name: Index.html delivered
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: Hello World
    - name: Open firewall
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
